name: finance_app
description: Finance App made as technical test.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.0
  dio: ^4.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.2.0
  flutter_bloc: ^7.3.3
  firebase_core: ^1.10.0
  fl_chart: ^0.40.2
  line_icons: ^2.0.1
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/config.json
    - assets/lotties/

  # Fonts
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf